version: '3'

services:
  questionnaire-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}